---
title: "Home"
author: "Columbia Psychology"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Welcome, Prospective Students!

We're thrilled that you're here. On this site, you will find everything you need for Prospective Student Days with the Columbia University psychology department. If any questions arise during your virtual visit, reach out to us anytime via [Slack](https://slack.com) or [email](mailto:psych-methods-support@columbia.edu){target="_blank"}.

## At a Glance

---

<div class="row">
<div class="col-md-9">
<h3 style="padding-top: 30px; margin-top: 0;">Today's Events (Wednesday, 2/17):</h3>
<table class="table table-striped">
<tr><td>6:00p onward</td><td><b>Welcome Social<br>(Prospective and Current<br>Graduate Students)</b></td><td><a href="https://www.kumospace.com/prospectives" target="_blank">Kumospace</a></td></tr>
</table>
<h3 style="padding-top: 30px; margin-top: 0;">Tomorrow's Events (Thursday, 2/18):</h3>
<table class="table table-striped">
<tr><td>10:00a - 10:30a</td><td><b>Information Session</b></td><td><a href="https://columbiauniversity.zoom.us/j/91757475604?pwd=QXNyd3RoSHJOb2JxbFpmaEhZN21UUT09" target="_blank">Zoom</a></td></tr>
<tr><td>10:30a - 11:00a</td><td>Break</td><td></td></tr>
<tr><td>11:00a - 11:40a</td><td><b>Faculty Meeting 1</b></td><td>Zoom (see email)</td></tr>
<tr><td>11:45a - 12:25p</td><td><b>Faculty Meeting 2</b></td><td>Zoom (see email)</td></tr>
<tr><td>12:30p - 1:10p</td><td>Break (Lunch)</td><td></td></tr>
<tr><td>1:15p - 2:25p</td><td><b>Faculty Meeting 3</b></td><td>Zoom (see email)</td></tr>
<tr><td>2:30p - 3:10p</td><td><b>Faculty Meeting 4</b></td><td>Zoom (see email)</td></tr>
</table>
To see the full schedule for Prospective Student Days, see the [Schedule](/schedule) page.
</div>
<div class="col-md-3">
<h3 style="padding-top: 30px; margin-top: 0;">Important Links:</h3>
- **[Kumospace](https://www.kumospace.com/prospectives){target="_blank"}**<br>(Social events)
- **[Slack](https://slack.com){target="_blank"}**<br>(Ongoing support)
- **Zoom**<br>Links will vary for Zoom meetings; see the [Schedule](/schedule) page for group meetings and your email for individual meetings

For more information on these links, see the [Resources](/resources) page.
</div>
</div>

## Welcome Video

---

<div class="video-container"><iframe width="640" height="390" src="https://www.youtube.com/embed/h52nyfxQ6hc?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>
