---
title: "Virtual Tour"
author: "Columbia Psychology"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Virtual Tour

## Campus and Morningside Heights

---

Although Columbia University was established in 1754, it moved throughout New York City several times before settling in 1897 in its current location in Morningside Heights, which is nestled between the Upper West Side and Harlem in the borough of Manhattan. Schermerhorn Hall, the location of the psychology department, is one of the original buildings in this current location. To learn more about our department and the university, check out the following virtual tour!

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/gMBROQDs6-w?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>

**Other useful resources**:

- [Columbia's Official Virtual Tour Website](https://undergrad.admissions.columbia.edu/visit/virtual-tours){target="_blank"}
- [A Guide to Morningside Heights as a Columbia Student](https://www.columbiaspectator.com/spectrum/2020/04/22/a-guide-to-morningside-heights-as-a-columbia-student/){target="_blank"}

## MBBI

---

Columbia recently opened its 450,000-square-foot home to the [Mortimer B. Zuckerman Mind Brain Behavior Institute](https://zuckermaninstitute.columbia.edu/){target="_blank"} in 2017. This state-of-the-art facility features three fMRI machines and houses several of the department's labs.

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/38TA2FycU2c?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>

## Housing

---

The university offers housing to graduate students for up to five years in apartment buildings near campus. There are several different kinds of units available, including apartment shares, studios, one bedrooms (for students who live with a spouse), and larger units (for students with children). For more specifics on the different kinds of units and eligibility, we recommend checking out [the Columbia Residential website](https://residential.columbia.edu/content/students/accommodations){target="_blank"}.

To give you a better sense of what it's like to live in Morningside Heights (as well as off-campus in Brooklyn), several students in the program have created tours featuring their housing. Please see below!

### One Bedroom Apartment Tour with Emily Nakkawita (4th Year):

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/zdrlbkj6_7M?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>

### One Bedroom Apartment Tour with Craig Poskanzer (1st Year):

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/525V4go64Bw?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>

### Studio Apartment Tour with Wenxuan Guo (2nd Year):

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/6oUv0q-jmuM?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>

### Apartment Share Tour with Yifan Yao (4th Year):

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/HatelBoLPbI?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>

### One Bedroom (Off-Campus Housing) Apartment Tour with Andrea Fields (5th Year):

<div class="video-container" style="margin-bottom:50px"><iframe width="640" height="390" src="https://www.youtube.com/embed/6NwxwxJJWL4?modestbranding=1&showinfo=0&rel=0&theme=light&color=white" frameborder="0"></iframe></div>
